name: restaurant_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^21.0.0-dev.2
  flutter_timezone: ^5.0.1
  google_fonts: ^8.0.1
  http: ^1.6.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  sqflite: ^2.4.2
  timezone: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
